function setupSDRT(modelName, Ts)

    if ~bdIsLoaded(modelName)
        load_system(modelName);
    end

    set_param(modelName, ...
        'SolverType','Fixed-step', ...
        'Solver','FixedStepDiscrete', ...
        'FixedStep',num2str(Ts), ...
        'ZeroCross','off', ...
        'EnableMultiTasking','off', ...
        'SignalLogging','off', ...
        'SystemTargetFile','grt.tlc', ...
        'InlineParams','on', ...
        'BlockReduction','on', ...
        'OptimizeSignalStorage','on', ...
        'HardwareBoard','Simulink Desktop Real-Time');

    save_system(modelName);
    fprintf('✔ SDRT configuration applied\n');
end
