function deployDesktopApp()
ws = warning('off', 'Compiler:compiler:COM_WARN_STARTUP_FILE_INCLUDED');
appFolder = fullfile(fileparts(mfilename("fullpath")), '..');
oc = onCleanup(@() warning(ws));
mlappPath = fullfile(appFolder, 'upCounter_SLSimApp.mlapp');
compiler.build.standaloneApplication(mlappPath, ...
	'AdditionalFiles', fullfile(appFolder, 'assets'), ...
	'SupportPackages', 'none', ...
	'OutputDir', fullfile(appFolder, 'deployedDesktopApp'));
Simulink.output.info(message("simulinkcompiler:genapp:FilesGeneratedAt", ...
	fullfile(appFolder, 'deployedDesktopApp')).string);
end
